version: "3.8"
services:
  blog-service:
    image: blog-app/blog
    restart: always
    build: .
    ports:
      - "${BLOG_APP_PORT}:8080"
    depends_on:
      - blogdb
    environment:
      MYSQL_HOST: ${BLOG_DB_HOST}
      MYSQL_USER: ${BLOG_DB_USER}
      MYSQL_PASSWORD: ${BLOG_DB_PASSWORD}
      MYSQL_PORT: ${BLOG_DB_PORT}
    networks:
      - blog-network
      - shared-network
  blogdb:
    image: mysql
    volumes:
      - blogdb_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${BLOG_DB_NAME}
      MYSQL_PASSWORD: ${BLOG_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${BLOG_DB_PASSWORD}
    networks:
      - blog-network
  auth-service:
    image: blog-app/auth
    restart: always
    ports:
      - "${AUTH_APP_PORT}:8081"
    depends_on:
      - userdb
    environment:
      MYSQL_HOST: ${USER_DB_HOST}
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_PORT: ${USER_DB_PORT}
    networks:
      - auth-network
      - shared-network
  userdb:
    image: mysql
    volumes:
      - userdb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD}
    networks:
      - auth-network

volumes:
  blogdb_data:
  userdb_data:

networks:
  blog-network:
  auth-network:
  shared-network:
