apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: blogs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-app
          image: ivanakoceva/auth-app
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_USER_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_PASSWORD
