apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blogs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog-app
          image: ivanakoceva/blog-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_BLOG_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_PASSWORD