apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: blogs
data:
  MYSQL_BLOG_HOST: "blogdb"
  MYSQL_USER_HOST: "userdb"
  MYSQL_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blogs
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog-app
          image: ivanakoceva/blog-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_BLOG_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: blogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-app
          image: ivanakoceva/auth-app
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_USER_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: MYSQL_PASSWORD
