apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blogs
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: blogs
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081