apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blogdb
  namespace: blogs
spec:
  serviceName: "blogdb"
  replicas: 1
  selector:
    matchLabels:
      app: blogdb
  template:
    metadata:
      labels:
        app: blogdb
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: blogdb-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: blogdb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi